---
# cPanel Git deployment for Angular app
# Replace USERNAME and (optionally) subfolder to match your account
# This deploys the built Angular assets from dist/project-angular/browser to public_html

deployment:
  tasks:
    # Set deploy target (edit this)
    - export DEPLOYPATH=/home/USERNAME/public_html/
    # Angular build output folder (default for Angular builder)
    - export ARTIFACTS=dist/project-angular/browser

    # OPTIONAL: Build on the server (requires Node.js + Angular CLI available on cPanel)
    # - /usr/local/bin/npm ci
    # - /usr/local/bin/npm run build

    # Ensure target exists
    - /bin/mkdir -p "$DEPLOYPATH"

    # OPTIONAL: Clean target except .htaccess (keeps config files intact)
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 -not -name ".htaccess" -exec /bin/rm -rf {} \;

    # Deploy build artifacts (copies directory contents without using wildcards)
    - /bin/cp -R "$ARTIFACTS"/. "$DEPLOYPATH"
